name: Build
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
      - name: Prerequisites
        run: apt-get update && apt-get install --no-install-recommends -y nodejs
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make
        run: make TARGET=NXDavSync -j
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: NXDavSync.nro
          path: NXDavSync.nro
